permissions: write-all # Equivalent to default permissions plus id-token: write
on:
  workflow_call:
    inputs:
      folder:
        type: string
        required: true
        description: The folder in which to run tests

env:
  AWS_REGION: us-west-2
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false

jobs:
  acceptance-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.folder }}-test-${{ github.sha }}-${{ matrix.index }}
      cancel-in-progress: false
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@v1
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-duration-seconds: 3600
          role-session-name: pulumi-tool-cdk-importer@githubActions
          role-to-assume: ${{ steps.esc-secrets.outputs.AWS_CI_ROLE_ARN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache-dependency-path: ./*.sum
      - name: Install Yarn
        run: curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
      - name: Run build
        run: make build
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - name: Generate go test Slice
        id: test_split
        uses: hashicorp-forge/go-test-split-action@v2.0.0
        with:
          working-directory: ${{ inputs.folder }}
          total: ${{ matrix.parallel }}
          index: ${{ matrix.index }}
      - name: Run ${{ inputs.folder }} tests
        # run: cd ${{ inputs.folder }} && gotestsum --format github-actions -- -v -count=1 -timeout 2h -parallel 4 -run "${{ steps.test_split.outputs.run }}"
        run: cd ${{ inputs.folder }} && go test -v -count=1 -timeout 1h -parallel 4 -run "${{ steps.test_split.outputs.run }}" ./...
    strategy:
      fail-fast: false
      matrix:
        parallel: [3]
        index: [0, 1, 2]
