name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags || true
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean -p 10 -f .goreleaser.yml --skip=validate --timeout 60m0s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
