permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PULUMI_API: https://api.pulumi-staging.io
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: imports/github-secrets
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: PULUMI_ACCESS_TOKEN
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch secrets from ESC
        id: esc-secrets
        uses: pulumi/esc-action@856b315abd3bf3849c64670704fbbcf275f386a2 # v1
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: build
        uses: ./.github/actions/build

  integration-test:
    name: integration-test
    secrets: inherit
    uses: ./.github/workflows/acceptance-tests.yml
    with:
      folder: integration

  sentinel:
    runs-on: ubuntu-latest
    name: sentinel
    steps:
    - name: Fetch secrets from ESC
      id: esc-secrets
      uses: pulumi/esc-action@856b315abd3bf3849c64670704fbbcf275f386a2 # v1
    - name: Mark workflow as successful
      uses: guibranco/github-status-action-v2@0849440ec82c5fa69b2377725b9b7852a3977e76
      with:
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: Sentinel
        state: success
        description: Sentinel checks passed
        sha: ${{ github.event.pull_request.head.sha || github.sha }}
    if: github.event_name == 'repository_dispatch' || github.event.pull_request.head.repo.full_name == github.repository
    needs:
    - build
    - integration-test

name: Run Acceptance Tests from PR
on:
  repository_dispatch:
    types: [run-acceptance-tests-command]
  pull_request:
    branches:
      - main
